# Generated by Django 3.0.3 on 2020-02-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudUserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
